# site settings
title: "総合コンテンツ制作サークル"
title_eng: "Comprehensive Contents Creators"
subtitle: "創造と表現"
email: 
description: "明治大学 中野キャンパスで活動している公認サークル"
baseurl: # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address:
city:
state:
zip_code:
country:
phone:

# homepage tiles
#tiles-source: posts # accepts "posts" or "pages" or "sokon"
tiles-count: 6
tiles-source: sokon

# social settings
twitter_url: "https://twitter.com/ccc_sokon"
blog_url: "http://sokon.hateblo.jp"
lineat_url: "https://line.me/R/ti/p/%40luq8751d"
atnd_url: "https://atnd.org/groups/sokon"
500px_url:
facebook_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:

# build settings
markdown: kramdown

sass:
  style: compressed

gems:
  - jekyll-redirect-from